/*---------------------------------------------------------------------

Template Name: 	Administry
Version:	 	1.0
Release Date: 	July 12, 2010

File:       	administry.js
Updated:    	2010-07-12

Copyright (c) 2010 Zoran Juric - http://themeforest.net/user/zoranjuric

-----------------------------------------------------------------------

WARNING! DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!

---------------------------------------------------------------------*/

// Preload images
imageObj = new Image();

// Administry object setup
if (!Administry) var Administry = {}

// scrollToTop() - scroll window to the top
Administry.scrollToTop = function (e) {
    $(e).hide().removeAttr("href");
    if ($(window).scrollTop() != "0") {
        $(e).fadeIn("slow")
    }
    var scrollDiv = $(e);
    $(window).scroll(function () {
        if ($(window).scrollTop() == "0") {
            $(scrollDiv).fadeOut("slow")
        } else {
            $(scrollDiv).fadeIn("slow")
        }
    });
    $(e).click(function () {
        $("html, body").animate({
            scrollTop: 0
        }, "slow")
    })
}

// setup() - Administry init and setup
Administry.setup = function () {
    // Open an external link in a new window
    $('a[href^="http://"]').filter(function () {
        return this.hostname && this.hostname !== location.hostname;
    }).attr('target', '_blank');
	
    // build animated dropdown navigation
	$('#menu ul').supersubs({ 
		minWidth:    12,   // minimum width of sub-menus in em units 
		maxWidth:    27,   // maximum width of sub-menus in em units 
		extraWidth:  1     // extra width can ensure lines don't sometimes turn over 
						   // due to slight rounding differences and font-family 
	}).superfish(); 
	
    // build an animated footer
    $('#animated').each(function () {
        $(this).hover(function () {
            $(this).stop().animate({
                opacity: 0.9
            }, 400);
        }, function () {
            $(this).stop().animate({
                opacity: 0.0
            }, 200);
        });
    });
	
	(function($,window,document){
'use strict';
var $Win=$(window);
jQuery.fn.extend({
	AutoFill:function(options,fn){
		return this.each(function(){
			if(!this.config){
			this.config = $.extend({
					Mode:"odd",//方式 单一:"only" 多个:"odd"
					Initial:"",//初始值 
					Json:""
				},options);
			} else if(options){this.config = $.extend(this.config, options);};
			
			var _Th=$(this),
				_Json=this.config.Json,
				_Number=this.config.Number,
				_Initial=this.config.Initial,
				_FillBox=_Th.find(".FillBox"),
				_FillTabs=$(".FillTabs"),
				_BitBox=$(".BitBox"),
				_FillCheck=$(".FillCheck"),
				_FillCloseImg=$(".FillCloseImg"),
				_FillChoose=$(".FillChoose"),
				_Filllist=$(".Filllist"),
				_MainInput=$(".MainInput"),
				_OnInput=$(".OnInput"),
				_FillFeed = $('.FillFeed'),
				_OffsetL=0,
				_OffsetT=0,
				_BitBoxVal=[];
			//初始数据
			var _InitialLength=_Initial.length;
			for(var i=0;i<_InitialLength;i++){
				_OnInput.before('<li class="BitBox" id="'+_Initial[i].id+'S">'+_Initial[i].name+'<a class="BitClose" href="#"></a><input type="hidden" value="'+_Initial[i].name+'"></li>');
			};
			//选中数组	
			var FnBitBox=function(){
				var _Length=_BitBox.length;
				for(var i=0;i<_Length;i++){
					var _Val=_BitBox.eq(i).find("input").val();
					_BitBoxVal.push(_Val);
				};
			};
			var FnAddItem = function(item, preadded){};
			var FnOffset=function(){
				_OffsetL=_FillBox.offset().left;
				_OffsetT=_FillBox.offset().top+_FillBox.innerHeight()+1;
			};
			_MainInput.live("click mousedown",function(){
				FnOffset()
				_FillChoose.show().css({"left":_OffsetL,"top":_OffsetT})
			});
			
			_FillCloseImg.click(function(){
				_FillChoose.hide()
			});
			
			//Tabs
			$(".FillTabs li:first-child").addClass("Active");
			$(".FillTabs li").live("click",function(){
				if($(this).attr('invalid')){return;}
				var _index = $(this).index();
				$(this).addClass("Active").siblings().removeClass("Active");
				$(this).parent(".FillTabs").next(".FillTabsCon").find(">div").eq(_index).stop(!0,!1).fadeIn().siblings().hide();
			});
			//多选
			_Filllist.click(function(event){
				event.preventDefault();			
				var _ID=$(this).attr("id");
				if(!$(this).hasClass("Active")){
					FnBitBox();
					$(this).addClass("Active");
					_OnInput.before('<li class="BitBox" id="'+_ID+'S">'+$(this).html()+'<a class="BitClose" href="#"></a><input type="hidden" value="'+$(this).html()+'"></li>');
					FnOffset();
					_FillChoose.css({"left":_OffsetL,"top":_OffsetT})
				}
				
			});
			
			for(h in options.hot_list){
				html+='<li rel="'+options.hot_list[h][0]+'"><a href="#'+h+'"><span>'+options.hot_list[h][2]+'</span>'+options.hot_list[h][1]+'</a></li>';
			}
			 
			// 查找城市
			function findCity(keyword) {
				var json = _Json;
				var tab,data,area,html="";
				for (var i = 1; i < json.length; i++) {
					tab = json[i] ;
					data = tab.datas;
					for (var j = 0; j < data.length; j++) {
						area = data[j];
						if (area.pin.toLowerCase().indexOf(keyword.toLowerCase()) == 0 || area.jian.toLowerCase().indexOf(keyword.toLowerCase()) == 0) {
							html+="<li class='FillFeedList'><span>"+area.pin+"</span>"+area.name+"</li>";
						}
					}
				}
				$(".FillFeed").html(html);
			}
			$(".BitBox").live("click",function() {
				$(this).fadeOut('fast',function() {
					$(this).remove();
				});
				return false;
			});
		})
		//end
	}
});
})(jQuery,window,document);

	
	/**多选*/
	$(".AreaList").each(function(){	
		var $Th=$(this),				
			_AreaList=$(".AreaList",$Th);
		_AreaList.find("dd").live("click",function(){
			if($(this).hasClass("Active")){
				$(this).removeClass("Active");
			}else{
				$(this).addClass("Active");
			}
		})
	});
	$(".Province").each(function(){	
		var $Th=$(this),				
			_AreaList=$(".Province",$Th);
		_AreaList.find("dd").live("click",function(){
			$(this).addClass("Active").siblings().removeClass("Active");
		})
	});
	

	/**文本框提示*/
	$(".InBox").each(function(){
			var $Th=$(this),
				_Time=3E2,
				_InExPlain=".InExplain",
				_InEnter=".InEnter",
				$InEnter=$Th.find(_InEnter),
				_InTip=$Th.find(".InTip"),
				_InTextBoxSpan=$Th.find(".InTextBox span"),
				_InenterVal=$InEnter.val(),
				_InNumber=$Th.find(".InNumber"),
				_Sum=_InNumber.find("em").eq(1).text(),
				_Length=_InenterVal.length;
			$Th.find(_InExPlain).css("line-height",$InEnter.innerHeight()+"px");
			$Th.find(_InNumber).css("line-height",$InEnter.innerHeight()+"px");
			if($InEnter.is("textarea")){
				$Th.find(_InExPlain).css("line-height","24px");
				if(Bro){$InEnter.width($InEnter.width());};
			};
			if($InEnter.val()){
				$Th.find(_InExPlain).hide();
			};
			var FnCount=function(Temp,Value){
				if (Temp <= -1) {//字数超出
					_InNumber.find("em").eq(0).html("<span class='CRed FB'>"+Value+"</span>");
				} else {
					_InNumber.find("em").eq(0).html(Value);
				};
			};
			//初始化文本框字数显示
			var _Result = _Sum - _Length;
			_InNumber.find("em").eq(0).html(_Length);
			FnCount(_Result,_Length);
			_InTip.live("keyup click mousedown",function(){
				$(this).find(_InExPlain).stop(!0,!1).fadeOut(_Time).end().find(_InEnter).focus();
				_InTextBoxSpan.stop(!0,!0).fadeIn();
			}).find(_InEnter).focus(function(){
				$(this).next(_InExPlain).stop(!0,!1).fadeOut(_Time);
			}).blur(function(){
				$(this).val()==''?$(this).next(_InExPlain).stop(!0,!0).fadeIn(_Time):$(this).next(_InExPlain).stop(true,false).fadeOut(_Time);
			});
			$InEnter.live("keyup keydown click mousedown keypress",function(){
				FnPress();
			});
			var FnPress=function() {
				var _Val = $InEnter.val();
				var _ValLength = _Val.length;
				var _Temp = _Sum - _ValLength;
				FnCount(_Temp,_ValLength);
			};
		});
	
	
	
    // scroll to top on request
    if ($("a#totop").length) Administry.scrollToTop("a#totop");

    // setup content boxes
    if ($(".content-box").length) {
        $(".content-box header").css({
            "cursor": "s-resize"
        });
        // Give the header in content-box a different cursor	
        $(".content-box header").click(
        function () {
            $(this).parent().find('section').toggle(); // Toggle the content
            $(this).parent().toggleClass("content-box-closed"); // Toggle the class "content-box-closed" on the content
        });
    }
	
	// setup nyro popup window
	$.nyroModalSettings({
		debug: false,
		processHandler: function(settings) {
			var url = settings.url;
			if (url && url.indexOf('http://www.youtube.com/watch?v=') == 0) {
				$.nyroModalSettings({
					type: 'swf',
					height: 355,
					width: 425,
					url: url.replace(new RegExp("watch\\?v=", "i"), 'v/')
				});
			}
		},
		endShowContent: function(elts, settings) {
			$('.resizeLink', elts.contentWrapper).click(function(e) {
				e.preventDefault();
				$.nyroModalSettings({
					width: Math.random()*1000,
					height: Math.random()*1000
				});
				return false;
			});
			$('.bgLink', elts.contentWrapper).click(function(e) {
				e.preventDefault();
				$.nyroModalSettings({
					bgColor: '#'+parseInt(255*Math.random()).toString(16)+parseInt(255*Math.random()).toString(16)+parseInt(255*Math.random()).toString(16)
				});
				return false;
			});
		}
	});
    
	// custom tooltips to replace the default browser tooltips for <a title=""> <div title=""> and <span title="">
    $("a[title], div[title], span[title]").tipTip();
}

// progress() - animate a progress bar "el" to the value "val"
Administry.progress = function (el, val, max) {
    var duration = 400;
    var span = $(el).find("span");
    var b = $(el).find("b");
    var w = Math.round((val / max) * 100);
    $(b).fadeOut('fast');
    $(span).animate({
        width: w + '%'
    }, duration, function () {
        $(el).attr("value", val);
        $(b).text(w + '%').fadeIn('fast');
    });
}

// videoSupport() - <video> tag support for older browsers through flash player embedding
Administry.videoSupport = function (wrapper, videoURL, width, height) {
    var v = document.createElement("video"); // Are we dealing with a browser that supports <video> tag? 
    if (!v.play) { // If no, use Flash.
        var vobj = $('#' + wrapper).find('video');
        var poster = $(vobj).attr("poster");
        var params = {
            allowfullscreen: "true",
            allowscriptaccess: "always"
        };
        var flashvars = {
            file: videoURL,
            image: poster
        };
        swfobject.embedSWF("player.swf", wrapper, width, height, "9.0.0", "expressInstall.swf", flashvars, params);
    }
}

// expandableRows() - expandable table rows
Administry.expandableRows = function () {
    var titles_total = $('td.title').length;
    if (titles_total) { /* setting z-index for IE7 */
        $('td.title').each(function (i, e) {
            $(e).children('div').css('z-index', String(titles_total - i));
        });

        $('td.title').find('a').click(function () {
            // hide previously opened containers
            $('.opened').hide();
            // remove highlighted class from rows
            $('td.highlighted').removeClass('highlighted');

            // locate the row we clicked onto
            var tr = $(this).parents("tr");
            var div = $(this).parent().find('.listingDetails');

            if (!$(div).hasClass('opened')) {
                $(div).addClass('opened').width($(tr).width() - 2).show();
                $(tr).find('td').addClass('highlighted');
            } else {
                $(div).removeClass('opened');
                $(tr).find('td').removeClass('highlighted');
            }
            return false;
        });
    }
}