/*---------------------------------------------------------------------

Template Name: 	Administry
Version:	 	1.0
Release Date: 	July 12, 2010

File:       	administry.js
Updated:    	2010-07-12

Copyright (c) 2010 Zoran Juric - http://themeforest.net/user/zoranjuric

-----------------------------------------------------------------------

WARNING! DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!

---------------------------------------------------------------------*/

// Preload images
imageObj = new Image();
var Bro = $.browser.msie && $.browser.version == "6.0";
// Administry object setup
if (!Administry) var Administry = {}
var EOC="easeOutCubic",
EIC="easeInCirc",
EOE="easeOutExpo",
EIE="easeInExpo",
EOQ="easeOutQuad",
EIQ="easeInQuint",
EIOB="easeInOutBack",
EIOQ="easeInOutQuart",
EIOE="easeInOutExpo",
$Const=0,
OPEN = OPEN || {
	Layer:8E3,
	Poplayer:"Poplayer",
	AnimTime:500,
	TransBox:function(Layer,ID){$("#"+ID).before('<div class="PF '+OPEN.Poplayer+'" style="z-index:'+Layer+'"></div>');
		$("."+OPEN.Poplayer).animate({opacity:"0.7"},OPEN.AnimTime,EOC);
	},
	/**弹出框
	* @param {String} ID:需要弹出框的ID
	*/
	Modal:function(ID){
		var $Th=$("#"+ID),_Width=$Th.width(),_Height=$Th.height();
		OPEN.TransBox(OPEN.Layer,ID);
		$Th.show().css({"z-index":++OPEN.Layer}).WinCon("In");
		$Th.find("select").removeClass("DisNo");
		if(Bro){$(".SelectIE").hide();};
		$(window).live("keydown",function(event){
			if(event.keyCode == 27){
				$Th.removeAttr("style").hide().BlankBox(1,_Width,_Height).prev("."+OPEN.Poplayer).animate({opacity:"0.1"},230,EOC,function(){
					$(this).remove();
				});
				$(window).unbind("keydown resize");
			};
		});
		return this;
	},
	clickShow:function(btn, cont, evt) {
		$(btn).each(function (i) {
			$(this).live(evt, function () {
				$(cont).slideToggle();
			});
		});
	},
	/**页面位置及窗口大小
	* @return {Array} 页面宽度PageW:_PageW,页面高度PageH:_PageH,窗口宽度WinW:_WinW,窗口高度WinH:_WinH
	*/
	GetPageSize:function(){
		var _ScrW="",_ScrH="";
		if(window.innerHeight && window.scrollMaxY){
			_ScrW = window.innerWidth + window.scrollMaxX;_ScrH = window.innerHeight + window.scrollMaxY;//Mozilla
		}else if(document.body.scrollHeight>document.body.offsetHeight){
			_ScrW = document.body.scrollWidth;_ScrH = document.body.scrollHeight;//all but IE Mac
		}else if(document.body){
			_ScrW = document.body.offsetWidth;_ScrH = document.body.offsetHeight;//IE Mac
		}
		var _WinW="",_WinH="";
		if(window.innerHeight){
			_WinW = window.innerWidth;_WinH = window.innerHeight;// all except IE
		}else if (document.documentElement && document.documentElement.clientHeight){
			_WinW = document.documentElement.clientWidth;_WinH = document.documentElement.clientHeight;// IE 6 Strict Mode
		}else if (document.body){
			_WinW = document.body.clientWidth;_WinH = document.body.clientHeight;//other
		}// for small pages with total size less then the viewport
		var _PageW = (_ScrW<_WinW) ? _WinW : _ScrW;
		var _PageH = (_ScrH<_WinH) ? _WinH : _ScrH;
		return {PageW:_PageW,PageH:_PageH,WinW:_WinW,WinH:_WinH};
	},
	/**滚动条位置
	* @return {Array} 滚动条X:x,滚动条Y:y
	*/
	GetPageScroll:function (){
		var x="",y="";
		if(window.pageYOffset){
			y = window.pageYOffset;x = window.pageXOffset;// all except IE
		}else if(document.documentElement && document.documentElement.scrollTop){
			y = document.documentElement.scrollTop;x = document.documentElement.scrollLeft;//IE 6 Strict
		}else if(document.body){
			y = document.body.scrollTop;x = document.body.scrollLeft;// all other IE
		}
		return {X:x,Y:y};
	},
	/**鼠标坐标
	* @return {Array} X轴坐标.x,Y轴坐标.y
	*/
	mousePosition:function (Event){
		if(Event.pageX || Event.pageY){
			return {x:Event.pageX, y:Event.pageY};
		}
		return {
			x:Event.clientX + document.body.scrollLeft - document.body.clientLeft,
			y:Event.clientY + document.body.scrollTop - document.body.clientTop
		};
	},
	/**图片头数据加载就绪事件 - 更快获取图片尺寸
	* @param {String} 图片路径
	* @param {function}	尺寸就绪
	* @param {function}	加载完毕 (可选)
	* @param {function}	加载错误 (可选)
	* @example ImgReady('http://www.google.com.hk/intl/zh-CN/images/logo_cn.png', function () {
			alert('size ready: width=' + this.width + '; height=' + this.height);
		});
	*/
	ImgReady:(function(){
		var _list = [], intervalId = null,		
		// 用来执行队列
		FnTick = function () {
			var i = 0;
			for (; i < _list.length; i++) {
				_list[i].end ? _list.splice(i--, 1) : _list[i]();
			};
			!_list.length && FnStop();
		},		
		// 停止所有定时器队列
		FnStop = function () {
			clearInterval(intervalId);
			intervalId = null;
		};		
		return function (url, ready, load, error) {
			var FnOnready, _Width, _Height, _NewWidth, _NewHeight,
				_Image = new Image();				
			_Image.src = url;		
			// 如果图片被缓存，则直接返回缓存数据
			if (_Image.complete) {
				ready.call(_Image);
				load && load.call(_Image);
				return;
			};				
			_Width = _Image.width;
			_Height = _Image.height;				
			// 加载错误后的事件
			_Image.onerror = function () {
				error && error.call(_Image);
				FnOnready.end = true;
				_Image = _Image.onload = _Image.onerror = null;
			};				
			// 图片尺寸就绪
			FnOnready = function () {
				_NewWidth = _Image.width;
				_NewHeight = _Image.height;
				if (_NewWidth !== _Width || _NewHeight !== _Height ||
					// 如果图片已经在其他地方加载可使用面积检测
					_NewWidth * _NewHeight > 1024
				) {
					ready.call(_Image);
					FnOnready.end = true;
				};
			};
			FnOnready();				
			// 完全加载完毕的事件
			_Image.onload = function () {
				// onload在定时器时间差范围内可能比FnOnready快
				// 这里进行检查并保证FnOnready优先执行
				!FnOnready.end && FnOnready();				
				load && load.call(_Image);					
				// IE gif动画会循环执行onload，置空onload即可
				_Image = _Image.onload = _Image.onerror = null;
			};		
			// 加入队列中定期执行
			if (!FnOnready.end) {
				_list.push(FnOnready);
				// 无论何时只允许出现一个定时器，减少浏览器性能损耗
				if (intervalId === null) intervalId = setInterval(FnTick, 40);
			};
		};
	})()
};
(function($,window,document){
	'use strict';
	var $Win=$(window);
	jQuery.fn.extend({
		ColorGradual:function(Degree,Time,Mode){
			return this.animate({opacity:Degree},Time,Mode);
		},
		ImgShow:function(){
			if($(document.getElementById("PicLarge")).length==0){
				$('<div class="PF '+OPEN.Poplayer+'" style="z-index:'+OPEN.Layer+'"/><div id="PicLarge" style="z-index:8899"><div id="PicLargeShow"><img id="PicLargeImg"/></div><div id="PicLargeLoad"/><a href="javascript:;" class="EB EBPicClose" id="IPicClose"></a></div>').appendTo('body');
				var $Th=$(this),
					_PicLarge=$(document.getElementById("PicLarge")),
					_PicShow=$(document.getElementById("PicLargeShow")),
					_PicLoad=$(document.getElementById("PicLargeLoad")),
					_PicImg=$(document.getElementById("PicLargeImg")),
					_PicClose=$(document.getElementById("IPicClose")),
					_WinSize=OPEN.GetPageSize();
				_PicLarge.css({
					width:"200",
					height:"200",
					"z-index":9999
				}).WinCon('Out');		
				Bro ? _PicShow.css({
					width:"0",
					height:"0",
					padding:"0",
					overflow:"hidden"
				}) : _PicShow.hide();
				$("."+OPEN.Poplayer).ColorGradual("0.8",6E2,EIC);
				var _Image = new Image,_Left=0,_Top=0,
				FnImgSize=function(){
					var _Width=_Left,_Height=_Top;
					if(_Width/_Height>=820/620){
						if(_Width>820){
							_Left=820;_Top=(_Height*820)/_Width;
						}else{
							_Left=_Width;_Top=_Height;
						}
					}else{
						if(_Height>620){
							_Top=620;_Left=(_Width*620)/_Height;
						}else{
							_Left=_Width;_Top=_Height;
						}
					};
				};
				_Image.src= $Th.attr("rel");
				OPEN.ImgReady(_Image.src,function(){
					_PicImg[0].src = this.src;
					_Left=this.width+20,_Top=this.height+20;
					FnImgSize();
					if(Bro){
						_PicLarge.css({width:_Left,height:_Top}).WinCon('Out',function(){
							_PicShow.removeAttr("style");
							if(_WinSize.WinH<_Top){
								_PicClose.css("top",(_Top-_WinSize.WinH)/2);
							}else{
								_PicClose.removeAttr("style");
							};
						});
						_PicLoad.hide();
					}else{
						_PicShow.show();
						_PicLoad.hide();
						_PicLarge.css({width:_Left,height:_Top}).WinCon('Out',function(){
							if(_WinSize.WinH<_Top){
								_PicClose.css("top",(_Top-_WinSize.WinH)/2);
							}else{
								_PicClose.removeAttr("style");
							};
						});
					};
					_Image.onload = null;
					_Image = null;
				});
				var FnImgShowClose=function(){
					_PicLarge.prev("."+OPEN.Poplayer).remove().end().remove();
				};
				_PicClose.click(function(){
					FnImgShowClose();
				});
				 return this;
			}
		},
		ModalClose:function(){
			var $Th=$(this).parents(".ModalBG"),_Width=$Th.width(),_Height=$Th.height();
			Body.removeClass("BodyLoad");
			$Win.unbind("keydown");
			$Th.removeAttr("style").hide().BlankBox(1,_Width,_Height).prev("."+OPEN.Poplayer).animate({opacity:"0.1"},230,EOC,function(){
				$(this).remove();
			});
			if(Bro){$Th.find("select").addClass("DisNo");$(".SelectIE").show();};
		},
		BlankBox:function(Mode,Width,Height,Scale){
			return this.each(function(){
				var $Th = $(this),
					FnTi="",
					_WinSize=OPEN.GetPageSize();
				$Th.after('<div class="BlankBox"/>');
				var _Blank=$(".BlankBox");
				var	FnIn = function (){
						var _Width=Width*Scale,_Height=Height*Scale;
						_Blank.css({
							width:_Width,
							height:_Height,
							left:(_WinSize.WinW-_Width)/2,
							top:(_WinSize.WinH-_Height)/2}
						).animate({
							width:Width,
							height:Height,
							left:(_WinSize.WinW-Width)/2,
							top:(_WinSize.WinH-Height)/2
						},200,EOE,function(){
							_Blank.remove();
						});
					};
				var	FnOut = function (){
						var _Width=_WinSize.WinW,_Height=0;
						_Blank.css({
							width:Width,
							height:10,
							left:(_WinSize.WinW-Width)/2,
							top:(_WinSize.WinH-10)/2
						}).animate({
							width:_Width,
							height:_Height,
							left:(_WinSize.WinW-_Width)/2,
							top:(_WinSize.WinH-_Height)/2
						},200,EOE,function(){
							_Blank.remove();
						});
					};
				if(Mode==0){
					FnTi = window.setTimeout(FnIn,0);
				};
				if(Mode==1){
					clearTimeout(FnTi);
					FnTi = window.setTimeout(FnOut,0);
				};
			});
		},
		WinCen:function(Mode,fn){
			return this.each(function(){
				var $Th = $(this),
					_WinSize=OPEN.GetPageSize(),
					_Width=$Th.width(),
					_Height=$Th.height();
				if(Mode=="Out"){
					$Th.css({left:(_WinSize.WinW-_Width)/2,top:(_WinSize.WinH-_Height)/2}).show(function(){
						if(fn){fn();};
					});
					if(Bro){
						var _ScrollTop = document.body.scrollTop + document.documentElement.scrollTop;
						var _Top = _ScrollTop + ((document.documentElement.clientHeight-_Height)/2);
						$Th.removeAttr("style").css({left:(_WinSize.WinW-_Width)/2,top:_Top,"z-index":OPEN.Layer++});
					}
					return true;
				};
				if(!Mode || Mode=="In"){
					$Th.BlankBox(0,_Width,_Height,1.5).css({left:(_WinSize.WinW-_Width)/2,top:(_WinSize.WinH-_Height)/2});
					if(Bro){
						$Th.removeAttr("style").BlankBox(0,_Width,_Height,1.5).css({left:(_WinSize.WinW-_Width)/2,"z-index":OPEN.Layer}).show();
					};
					return true;
				};
			});
		},
		WinCon:function(Mode,fn){
			return this.each(function(){
				var $Th = $(this);
				$Th.WinCen(Mode,fn);
				$Win.live("resize",function(){
					var _WinSize=OPEN.GetPageSize(),_Width=$Th.width(),_Height=$Th.height();
					$Th.stop(!0,!1).animate({left:(_WinSize.WinW-_Width)/2,top:(_WinSize.WinH-_Height)/2},6E2,EIOB,function(){
						if(fn){fn();};
					});
				});
			});
		}
	});
})(jQuery,window,document);
function AutoFill(th,Multi,Maxnum,Modalid,Initial,FilterArray){
	var $Th=$(th),
		_FillChoose=$(Modalid),
		_FillFeed=_FillChoose.find(".FillFeed"),
		_FillCheck=_FillChoose.find(".FillCheck"),
		_AutoFill=$Th.find(".AutoFill"),
		_FillCloseImg=$(".FillCloseImg"),
		_OffsetL=0,
		_OffsetT=0;
		//_BitBoxVal=[];
	 $Th.append('<div class="FillBox" style="width:'+$Th.innerWidth()+'px"><a class="BitInput"><input type="text" class="MainInput"/></a></div>').find(".AutoFill").hide(); 
	//添加项
	var FnAddItem = function(text){
		var _html='<a class="BitBox" href="javascript:;">'+text+'<b class="I"></b></a>';
		if($Th.find(".FillBox").find(".BitBox").length<Maxnum && Multi){		
			$Th.find(".BitInput").before(_html);
		};
		if(!Multi){
			_FillCloseImg.click();
			$Th.find(".BitInput").siblings().remove().end().before(_html);
		};
		FnFillTxt();
	},
	FnFillTxt = function(){
		var _Txt=new Array();
		$Th.find(".FillBox").find(".BitBox").each(function(){
			_Txt.push($(this).text());
		});
		_AutoFill.val(_Txt.join(","));
	};
	
	//初始数据
	if(Initial){
		var _InitialLength=Initial.length;
		for(var i=0;i<_InitialLength;i++){
			FnAddItem(Initial[i].name)
		};
	}
	//计算位置
	var FnOffset=function(){
		_OffsetL = $Th.find(".FillBox").offset().left;
		_OffsetT = $Th.find(".FillBox").offset().top+$Th.find(".FillBox").innerHeight()+4;
	};
	//关闭框
	_FillCloseImg.click(function(){
		_FillChoose.hide();
		_FillChoose.find(".FillClick").unbind("click");
		if(Bro){$(".SelectIE").show();};
	});
	var FnMulti=function(){
		//多选
		_FillChoose.find(".FillClick").live("click",function(event){
			event.preventDefault();	
			var _ID=$.trim($(this).text());
			var _BitBox = $Th.find(".FillBox").find(".BitBox");
			var _Skip = false;
			_BitBox.each(function(){
				var _Sn = $.trim($(this).text());	
				if(_Sn==_ID){
					_Skip=true;
					return;
				};
			});				
			if(_Skip){return};
			$Th.find(".MainInput").focus();
			FnAddItem(_ID,$(this).html());
			FnOffset();
			_FillChoose.css({"left":_OffsetL,"top":_OffsetT});
		});				
	};
	//点击框
	$Th.find(".FillBox").live("click",function(){			
		$Th.find(".MainInput").focus();
		FnOffset();
		_FillCloseImg.click();
		_FillChoose.show().css({"left":_OffsetL,"top":_OffsetT});
		if(Bro){$(".SelectIE").hide();};
		FnMulti();			
	});	
	//查找城市		
	$Th.find(".MainInput").live("keypress keydown keyup",function(){
		$(this).val("");return;
		if($(this).val()==""){
			_FillCheck.show();
			_FillFeed.hide();				
		}else{
			_FillFeed.css({'overflow':'auto'}).show();
			_FillCheck.hide();
			_FillFeed.find("dt").text($(this).val());
			findCity($(this).val());
		};
	});

	$(document).live("click",".BitBox",function(event){
		event.stopPropagation();    
		$(this).fadeOut('fast',function() {
			$(this).remove();
			FnFillTxt();
		});				
		return false;
	});
	$(document.body).click(function(e) {
		var target = e.target;
		var needClose = true;			
		$(".FillBox,FillBox *").each(function(){
			if(this==target){
				needClose = false;
				return;
			}
		});			
		$('.FillChoose').find('*').each(function(){
			if(this==target){
				needClose = false;
				return;
			}
		});			
		if(needClose){
			_FillCloseImg.click();
		}
		return true;
	});
	$Th.find(".MainInput").live("keyup",function(event){
		var _Evevt = event.target||event.srcElement;
		if(event.keyCode == 8){
			$(this).parent().prev().remove();
		};
	});
}

function GetPageScroll(){
	var x="",y="";
	if(window.pageYOffset){
		y = window.pageYOffset;x = window.pageXOffset;// all except IE
	}else if(document.documentElement && document.documentElement.scrollTop){
		y = document.documentElement.scrollTop;x = document.documentElement.scrollLeft;//IE 6 Strict
	}else if(document.body){
		y = document.body.scrollTop;x = document.body.scrollLeft;// all other IE
	}
	return {X:x,Y:y};
}

// scrollToTop() - scroll window to the top
Administry.scrollToTop = function (e) {
    $(e).hide().removeAttr("href");
    if ($(window).scrollTop() != "0") {
        $(e).fadeIn("slow")
    }
    var scrollDiv = $(e);
    $(window).scroll(function () {
        if ($(window).scrollTop() == "0") {
            $(scrollDiv).fadeOut("slow")
        } else {
            $(scrollDiv).fadeIn("slow")
        }
    });
    $(e).click(function () {
        $("html, body").animate({
            scrollTop: 0
        }, "slow")
    })
}

// setup() - Administry init and setup
Administry.setup = function () {
	self.Body=$("body");
	self.Doc=document;
	self.$Doc=$(document);
	self.Win=$(window);
	
    // Open an external link in a new window
    $('a[href^="http://"]').filter(function () {
        return this.hostname && this.hostname !== location.hostname;
    }).attr('target', '_blank');
	
    // build animated dropdown navigation
	$('#menu ul').supersubs({ 
		minWidth:    12,   // minimum width of sub-menus in em units 
		maxWidth:    27,   // maximum width of sub-menus in em units 
		extraWidth:  1     // extra width can ensure lines don't sometimes turn over 
						   // due to slight rounding differences and font-family 
	}).superfish(); 
	
    // build an animated footer
    $('#animated').each(function () {
        $(this).hover(function () {
            $(this).stop().animate({
                opacity: 0.9
            }, 400);
        }, function () {
            $(this).stop().animate({
                opacity: 0.0
            }, 200);
        });
    });
	
	/**输入框提示*/
	$(".IBoxTip,.TBoxTip,.NavSearchBox").each(function () {
		var _Label="label",_Input="input",_IPrompt="IPrompt",_Time=3E2;
		$(this).each(function(){
			var $Th=$(this);
			$Th.find(_Label).css("line-height",$Th.find(_Input).outerHeight()+"px");
			if($Th.find(_Input).val()){$Th.find(_Label).hide();};
		})
		.click(function(){$(this).find("."+_IPrompt).fadeIn().end().find(_Label).stop(!0,!1).fadeOut(_Time).end().find(_Input).focus();})
		.find(_Input).focus(function(){$(this).next(_Label).stop(!0,!1).fadeOut(_Time).end().parent().find("."+_IPrompt).fadeIn();})
		.blur(function(){
			if($(this).val()==''){
				$(this).next(_Label).fadeIn(_Time).next("."+_IPrompt).fadeOut();
			}else{
				$(this).next(_Label).stop(!0,!1).fadeOut(_Time).next("."+_IPrompt).fadeOut();
			}
		});
	});

    
	$(".AreaList").each(function(){	
		var $Th=$(this),				
			_AreaList=$(".AreaList",$Th);
		_AreaList.find("dd").live("click",function(){
			if($(this).hasClass("Active")){
				$(this).removeClass("Active");
			}else{
				$(this).addClass("Active");
			}
		})
	});
	$(".Province").each(function(){	
		var $Th=$(this),				
			_AreaList=$(".Province",$Th);
		_AreaList.find("dd").live("click",function(){
			$(this).addClass("Active").siblings().removeClass("Active");
		})
	});
	
	if($(".LineTab").length>0){
		var $Th=$(".LineTab"),
			_Top= $Th.parent().offset().top;
		$Th.find("li").eq(0).addClass("Current").siblings().removeClass("Current");
		if(!Bro){
			$(window).scroll(function(){
				var _Scroll=GetPageScroll();
				var _ScrollTop = _Scroll.Y;						
				if(_ScrollTop >= _Top ){
					$Th.addClass("PF");
				}else if(_ScrollTop <= _Top){
					$Th.removeClass("PF");
				};
				var _List = $(".LineTabTi");
				_List.each(function(index) {
					var _Th = $(this);
					var _ThTop = _Th.offset().top;
					if (_ThTop -35 >= _ScrollTop && _ScrollTop > _Top) {
						var _Index = _List.index(this);
						if (index > 0) {
							$Th.find("li").eq(index - 1).addClass("Current").siblings().removeClass("Current");
						}
						return false;
					} else if (_List.index(this) >= $(".LineTab").find("li").length - 2 && _ScrollTop > _Top) {
						var _Index = _List.index(this);
						$Th.find("li").eq(_Index).addClass("Current").siblings().removeClass("Current");
					}
				});
			});	
		}
		$Th.find("li").click(function(){
			var _Index = $(this).index();
			var _To = $(".LineTabTi").eq(_Index).offset().top-33;
			$('html, body').animate({scrollTop:_To},50);
		});			
	};	
	//Tabs
	$(".Tabs li:first-child").addClass("Active");
	$(".Tabs li").live("click",function(){
		if($(this).attr('invalid')){
			return;
		}
		var _index = $(this).index();
		$(this).addClass("Active").siblings().removeClass("Active");
		$(this).parent(".Tabs").next(".TabsCon").find(">div").eq(_index).stop(!0,!1).fadeIn().siblings().hide();
	});

	/**�ı�����ʾ*/
	$(".InBox").each(function(){
			var $Th=$(this),
				_Time=3E2,
				_InExPlain=".InExplain",
				_InEnter=".InEnter",
				$InEnter=$Th.find(_InEnter),
				_InTip=$Th.find(".InTip"),
				_InTextBoxSpan=$Th.find(".InTextBox span"),
				_InenterVal=$InEnter.val(),
				_InNumber=$Th.find(".InNumber"),
				_Sum=_InNumber.find("em").eq(1).text(),
				_Length=_InenterVal.length;
			$Th.find(_InExPlain).css("line-height",$InEnter.innerHeight()+"px");
			$Th.find(_InNumber).css("line-height",$InEnter.innerHeight()+"px");
			if($InEnter.is("textarea")){
				$Th.find(_InExPlain).css("line-height","24px");
			};
			if($InEnter.val()){
				$Th.find(_InExPlain).hide();
			};
			var FnCount=function(Temp,Value){
				if (Temp <= -1) {//��������
					_InNumber.find("em").eq(0).html("<span class='CRed FB'>"+Value+"</span>");
				} else {
					_InNumber.find("em").eq(0).html(Value);
				};
			};
			//��ʼ���ı���������ʾ
			var _Result = _Sum - _Length;
			_InNumber.find("em").eq(0).html(_Length);
			FnCount(_Result,_Length);
			_InTip.live("keyup click mousedown",function(){
				$(this).find(_InExPlain).stop(!0,!1).fadeOut(_Time).end().find(_InEnter).focus();
				_InTextBoxSpan.stop(!0,!0).fadeIn();
			}).find(_InEnter).focus(function(){
				$(this).next(_InExPlain).stop(!0,!1).fadeOut(_Time);
			}).blur(function(){
				$(this).val()==''?$(this).next(_InExPlain).stop(!0,!0).fadeIn(_Time):$(this).next(_InExPlain).stop(true,false).fadeOut(_Time);
			});
			$InEnter.live("keyup keydown click mousedown keypress",function(){
				FnPress();
			});
			var FnPress=function() {
				var _Val = $InEnter.val();
				var _ValLength = _Val.length;
				var _Temp = _Sum - _ValLength;
				FnCount(_Temp,_ValLength);
			};
		});
	
	
	
    // scroll to top on request
    if ($("a#totop").length) Administry.scrollToTop("a#totop");

    // setup content boxes
    if ($(".content-box").length) {
        $(".content-box header").css({
            "cursor": "s-resize"
        });
        // Give the header in content-box a different cursor	
        $(".content-box header").click(
        function () {
            $(this).parent().find('section').toggle(); // Toggle the content
            $(this).parent().toggleClass("content-box-closed"); // Toggle the class "content-box-closed" on the content
        });
    }
	
	// setup nyro popup window
	$.nyroModalSettings({
		debug: false,
		processHandler: function(settings) {
			var url = settings.url;
			if (url && url.indexOf('http://www.youtube.com/watch?v=') == 0) {
				$.nyroModalSettings({
					type: 'swf',
					height: 355,
					width: 425,
					url: url.replace(new RegExp("watch\\?v=", "i"), 'v/')
				});
			}
		},
		endShowContent: function(elts, settings) {
			$('.resizeLink', elts.contentWrapper).click(function(e) {
				e.preventDefault();
				$.nyroModalSettings({
					width: Math.random()*1000,
					height: Math.random()*1000
				});
				return false;
			});
			$('.bgLink', elts.contentWrapper).click(function(e) {
				e.preventDefault();
				$.nyroModalSettings({
					bgColor: '#'+parseInt(255*Math.random()).toString(16)+parseInt(255*Math.random()).toString(16)+parseInt(255*Math.random()).toString(16)
				});
				return false;
			});
		}
	});
    
	// custom tooltips to replace the default browser tooltips for <a title=""> <div title=""> and <span title="">
    $("a[title], div[title], span[title]").tipTip();
}

// progress() - animate a progress bar "el" to the value "val"
Administry.progress = function (el, val, max) {
    var duration = 400;
    var span = $(el).find("span");
    var b = $(el).find("b");
    var w = Math.round((val / max) * 100);
    $(b).fadeOut('fast');
    $(span).animate({
        width: w + '%'
    }, duration, function () {
        $(el).attr("value", val);
        $(b).text(w + '%').fadeIn('fast');
    });
}

// videoSupport() - <video> tag support for older browsers through flash player embedding
Administry.videoSupport = function (wrapper, videoURL, width, height) {
    var v = document.createElement("video"); // Are we dealing with a browser that supports <video> tag? 
    if (!v.play) { // If no, use Flash.
        var vobj = $('#' + wrapper).find('video');
        var poster = $(vobj).attr("poster");
        var params = {
            allowfullscreen: "true",
            allowscriptaccess: "always"
        };
        var flashvars = {
            file: videoURL,
            image: poster
        };
        swfobject.embedSWF("player.swf", wrapper, width, height, "9.0.0", "expressInstall.swf", flashvars, params);
    }
}

// expandableRows() - expandable table rows
Administry.expandableRows = function () {
    var titles_total = $('td.title').length;
    if (titles_total) { /* setting z-index for IE7 */
        $('td.title').each(function (i, e) {
            $(e).children('div').css('z-index', String(titles_total - i));
        });

        $('td.title').find('a').click(function () {
            // hide previously opened containers
            $('.opened').hide();
            // remove highlighted class from rows
            $('td.highlighted').removeClass('highlighted');

            // locate the row we clicked onto
            var tr = $(this).parents("tr");
            var div = $(this).parent().find('.listingDetails');

            if (!$(div).hasClass('opened')) {
                $(div).addClass('opened').width($(tr).width() - 2).show();
                $(tr).find('td').addClass('highlighted');
            } else {
                $(div).removeClass('opened');
                $(tr).find('td').removeClass('highlighted');
            }
            return false;
        });
    }
}

window.isCtrlKey = function (keyCode, ignore) {
    // 8        - 退格
    // 9        - Tab
    // 13       - 回车
    // 16~18    - Shift, Ctrl, Alt
    // 37~40    - 左上右下
    // 35~36    - End Home
    // 46       - Del
    // 112~123  - F1-F12
	if (("," + ignore.join() + ",").indexOf("," + keyCode + ",") != -1) {
		return false;
	}

    switch (keyCode) {
        case 8: case 9: case 13:
        case 16: case 17: case 18:
        case 37: case 38: case 39: case 40:
        case 35: case 36: case 46:
            return true;
        default:
            if (keyCode >= 112 && keyCode <= 123) {
                return true;
            }
    		return false;
	}
}